### ISSUE TITLE
Module not save attributes in the database

### ISSUE THREAD

**Issue by EdwardNavarro** [sgomez/simplesamlphp-module-oauth2#5] opened 2017-02-13 02:37 UTC
Hi @sgomez 

I cant get the attributes configured in the config file, the module not save this info in the "attributes" in the database and my SP app can't receive this in the userinfo.php response. I use LDAP auth source.

**Comment by stamatisv** [comment] 2017-02-25 15:50
Same issue for me. I did some quick testing, for some reason when I chose implicit grant, the values are stored correctly in db. With authorization code grant (explicit) , the attributes in the db are stored empty []. I will dig it more next few days. @EdwardNavarro did you find anything?

**Comment by sgomez** [comment] 2017-02-25 15:59
Sorry, I was very busy this days and I had not free time to work on this. Anyway, I'm try to solve it this weekend. Thanks @stamatisv for the clue. 

Please, can send me the result of 'composer info' command?

**Comment by sgomez** [comment] 2017-02-25 17:08
Yes, this is a bad implementation of the explicit grant. Sorry. The problem is that I write the attributes when the access token is created and in explicit grant this happens between the webserver and the oauth2 server communication. I have no access to the simplesaml cookie to get the attributes and that is the reason that the attributes are empty on the table.

I need to review the code and see when I did the mistake. I'm working on it.

**Comment by stamatisv** [comment] 2017-02-25 17:25
Sergio, thank you for the (really) quick response, glad I gave you a clue about this.

**Comment by sgomez** [comment] 2017-02-25 18:47
@EdwardNavarro @stamatisv I did a new commit but I need to work more on it. Anyway I probe it and it works. 

If you want to try, you have to change to master-dev version in your composer.json (or install the master branch manually in modules directory).

Two questions:

1. I only work with master branch of simplesamlphp (1.14 version is too old for me).
2. You need to update the schema, because now I'm saving the attributes in a new table. You need to run this: again ```php ./vendor/bin/dbalschema``` (maybe you need to purge the tables before do it).

I hope to have more time to close this next week.

**Comment by stamatisv** [comment] 2017-02-25 19:20
@sgomez I did switch to the dev-master branch and updated source, purged db and rerun the schema generation script. I can confirm that now I can get the attributes with authorization code grant.

Keep up the good work!

**Comment by EdwardNavarro** [comment] 2017-02-27 16:12
Hi guys, thanks for your time trying to resolve this issue. I get the same issue, I does all @sgomez says and try again but the issue persist, the attributes aren't saved into the db. I use LDAP as authsource and configure this to get all attributes of the user but the OAuth2 module can't save this on the db. I need to configure the module_oauth2.php different to default? I only can get username attribute.

All your help is appreciated.

**Comment by stamatisv** [comment] 2017-02-27 17:13
Hello Edward, did you update the source through composer or did you grab the latest zip?
What I did exactly:
1) changed at simplesamlphp root , composer.json : 
"sgomez/simplesamlphp-module-oauth2": "dev-master"
2) run composer update , files got updated
3) purged my db and recreated schema using 
vendor/bin/dbalschema
4) created new client/secret/etc through web 

Then I performed my tests again, this time I get all attributes for all grants ( I have also added refresh token grant ) .
I use both custom authsource and ldap.

**Comment by sgomez** [comment] 2017-02-27 18:38
@EdwardNavarro [this is the line where the module gets the attributes](https://github.com/sgomez/simplesamlphp-module-oauth2/blob/master/www/authorize.php#L26). This value will be saved in the user table (the new table I created in the last commit: SimpleSAMLphp_oauth2_user). You can do a dump + die to check the attributes that you get from the authsource.

Anyway, you can test your authsource too in your server and check how many attributes do you receive:
http://yourserver/simplesaml/module.php/core/authenticate.php

**Comment by EdwardNavarro** [comment] 2017-02-27 23:09
@sgomez @stamatisv thanks so much for your help guys, i followed all indications and initially this not worked. After many tests i found the problem is the LDAP source configuration. The problem was that i set ldap attributes to "NULL" to fetch all attributes. When I set this to "ej. attributes = cn, givenName, mail, etc..." the problem has been solved. Not work if i try to get all attributes from LDAP, i have to define some specific attributes manually. Now the module store the attributes in the db and all work fine. Thanks! Regards from Colombia.

![screen shot 2017-02-27 at 6 10 53 pm](https://cloud.githubusercontent.com/assets/1706334/23384268/20cfb5ac-fd18-11e6-8cb6-50eceba5f7f5.png)

**Comment by sgomez** [comment] 2017-02-28 12:09
@EdwardNavarro this is so strange. Please, can you confirm if you see all attributes on the simplesaml backend when you use ```null```? (in the Test authentication sources pages http://localhost/simplesaml/module.php/core/authenticate.php).

I tried with my own LDAP Server and it works with null parameter.

**Comment by EdwardNavarro** [comment] 2017-02-28 14:45
@sgomez yes, I tryed again today to re-confirm, and the result is same.

LDAP attributes: NULL   >>>   None attributes saved on the db
LDAP attributes: Specific manually selected (ex: cn, givenName, sn, mail, etc...)  >>>  defined attributes saved on db.

In two scenarios, when I test in "Test authentication sources pages http://localhost/simplesaml/module.php/core/authenticate.php" I can see the attributes, all or selected according to the case.

I use the LDAP module to access to a AD on windows server, the login works perfect and the attributes are fetched correctly. You think maybe the AD instead of LDAP regular server can cause the problem?

**Comment by stamatisv** [comment] 2017-02-28 21:34
I know it's not helpful but I thought I would share my test:
using OpenLDAP and setting  'attributes' => NULL,
the db gets populated correctly with all attributes.

**Comment by EdwardNavarro** [comment] 2017-02-28 21:41
Interesting, i will make a test in our test server using OpenLDAP and tell you how it's going.

**Comment by sgomez** [comment] 2017-04-04 21:19
I did two new releases. From now, you can use ^1.0 for SimpleSAMLphp 1.14 and ^2.0 for master branch.

Please, see the [README.md](https://github.com/sgomez/simplesamlphp-module-oauth2/blob/master/README.md) file.

**Closed as completed by sgomez** 2017-04-04 21:19 UTC
Labels: bug
